### Two Dimensional Array

In [6]:
import numpy as np

In [8]:
simple_matrix=np.array([[67,78,89,67],[25,35,45,55],[47,57,67,77]])
simple_matrix

array([[67, 78, 89, 67],
       [25, 35, 45, 55],
       [47, 57, 67, 77]])

In [9]:
simple_matrix[2,:]

array([47, 57, 67, 77])

In [11]:
simple_matrix[2,2]

67

In [13]:
simple_matrix[:,(2,3)]

array([[89, 67],
       [45, 55],
       [67, 77]])

### Simple_Array in numpy

In [15]:
simple_array=np.arange(1,20)
simple_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [16]:
simple_array+simple_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [18]:
np.exp(simple_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [19]:
np.square(simple_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [20]:
np.min(simple_array)

1

In [21]:
np.max(simple_array)

19

In [22]:
np.argmax(simple_array)

18

In [23]:
np.sqrt(simple_array)


array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [24]:
np.var(simple_array)

30.0

In [25]:
np.sum(simple_array)

190

In [26]:
np.mean(simple_array)

10.0

In [27]:
np.log(simple_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [39]:
array=np.random.rand(3,4)
array

array([[0.14557298, 0.99787863, 0.22341602, 0.51918018],
       [0.21477829, 0.02344473, 0.87256146, 0.29142756],
       [0.21139085, 0.37503363, 0.56111506, 0.67128518]])

In [41]:
np.round(array,decimals=2)

array([[0.15, 1.  , 0.22, 0.52],
       [0.21, 0.02, 0.87, 0.29],
       [0.21, 0.38, 0.56, 0.67]])

In [43]:
friends=np.array(["rajesh","shashikanth","uthkarsh","sangamesh","nanda","vivek","nanda","vivek"])
np.unique(friends)

array(['nanda', 'rajesh', 'sangamesh', 'shashikanth', 'uthkarsh', 'vivek'],
      dtype='<U11')